version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/node/app
      - /usr/node/app/node_modules
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
